# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://nicoelbert.github.io/fastai_nbdev_test/"

git_url = "https://github.com/nicoelbert/fastai_nbdev_test/master"

def custom_doc_links(name): return None
